### ISSUE TITLE
[Bug][Linux] crash after end of Dark Tide 1 Mod

### ISSUE THREAD

**Issue by mlauss2** [luciusDXL/TheForceEngine#204]
Play the Dark Tide 1 mod to the end, then hit ESC and select Next Mission.
TFE (Linux) crashes because it hits the assert(0) at TheForceEngine/TFE_Jedi/Task/task.cpp:244  (about to free a subtask)

relevant trace:
tfelnx: TheForceEngine/TFE_Jedi/Task/task.cpp:244: void TFE_Jedi::task_free(Task*): Assertion `0' failed.
Thread 1 "tfelnx" received signal SIGABRT, Aborted.
#5  0x0000555555645aea in TFE_Jedi::task_free (task=0x55555d567378) at TheForceEngine/TFE_Jedi/Task/task.cpp:244
#6  0x0000555555645b58 in TFE_Jedi::ctxReturn () at TheForceEngine/TFE_Jedi/Task/task.cpp:379
#7  0x00005555555c9d3c in TFE_DarkForces::mission_mainTaskFunc (msg=MSG_RUN_TASK) at TheForceEngine/TFE_DarkForces/mission.cpp:618

**Comment by mlauss2** [comment]
The following seems to be a working fix:

```diff
diff --git a/TheForceEngine/TFE_Jedi/Task/task.cpp b/TheForceEngine/TFE_Jedi/Task/task.cpp
index ef648b19..ac1c6599 100644
--- a/TheForceEngine/TFE_Jedi/Task/task.cpp
+++ b/TheForceEngine/TFE_Jedi/Task/task.cpp
@@ -241,7 +241,8 @@ namespace TFE_Jedi
                if (task->subtaskNext)
                {
                        // Should we free subtasks?
-                       assert(0);
+                       task_free(task->subtaskNext);
+                       task->subtaskNext = nullptr;
                }
                // If this task was the subtaskNext, then move the next subtask into that role.
                Task* parent = task->subtaskParent;


```

**Comment by mlauss2** [comment]
I can no longer reproduce it after some unrelated changes to other source files and a compiler update.
